export const BASE = '||||||| BASE'
export const LOCAL = '<<<<<<< LOCAL'
export const NEWLINE = '\n'
export const REMOTE = '>>>>>>> REMOTE'
export const SEPARATOR = '======='
export const TEXT_TAG = '#text'
