export const KEY_FIELD_METADATA = {
  marketingAppExtActivities: 'fullName',
  alerts: 'fullName',
  fieldUpdates: 'fullName',
  flowActions: 'fullName',
  outboundMessages: 'fullName',
  rules: 'fullName',
  knowledgePublishes: 'fullName',
  tasks: 'fullName',
  send: 'fullName',
  sharingCriteriaRules: 'fullName',
  sharingGuestRules: 'fullName',
  sharingOwnerRules: 'fullName',
  sharingTerritoryRules: 'fullName',
  assignmentRule: 'fullName',
  autoResponseRule: 'fullName',
  escalationRule: 'fullName',
  matchingRules: 'fullName',
  valueTranslation: 'masterLabel',
  categoryGroupVisibilities: 'dataCategoryGroup',
  applicationVisibilities: 'application',
  classAccesses: 'apexClass',
  customMetadataTypeAccesses: 'name',
  customPermissions: 'name',
  customSettingAccesses: 'name',
  externalDataSourceAccesses: 'externalDataSource',
  fieldPermissions: 'field',
  flowAccesses: 'flow',
  loginFlows: 'friendlyname',
  layoutAssignments: '<object>',
  loginHours: '<array>',
  loginIpRanges: '<array>',
  objectPermissions: 'object',
  pageAccesses: 'apexPage',
  profileActionOverrides: 'actionName',
  recordTypeVisibilities: 'recordType',
  tabVisibilities: 'tab',
  userPermissions: 'name',
  bots: 'fullName',
  customApplications: 'name',
  customLabels: 'name',
  customPageWebLinks: 'name',
  customTabs: 'name',
  flowDefinitions: 'fullName',
  pipelineInspMetricConfigs: 'name',
  prompts: 'name',
  quickActions: 'name',
  reportTypes: 'name',
  scontrols: 'name',
  standardValue: 'fullName',
  customValue: 'fullName',
  labels: 'fullName',
}

export const METADATA_TYPES_PATTERNS = [
  'assignmentRules',
  'autoResponseRules',
  'escalationRules',
  'globalValueSet',
  'globalValueSetTranslation',
  'marketingappextension',
  'matchingRule',
  'profile',
  'sharingRules',
  'standardValueSet',
  'standardValueSetTranslation',
  'workflow',
]
