---
name: Package dev version cleaner

on:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "img/**"
    types:
      - closed

jobs:
  get-pr-info:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    outputs:
      dev_channel: ${{ steps.set-dev-channel.outputs.DEV_CHANNEL }}
    steps:
      - uses: jwalton/gh-find-current-pr@master
        id: pr-number
        with:
          state: closed

      - name: Set dev channel value
        id: set-dev-channel
        run: echo "DEV_CHANNEL=dev-${{ steps.pr-number.outputs.pr }}" >> "$GITHUB_OUTPUT"

  cleanup:
    needs: [get-pr-info]
    if: ${{ github.event.pull_request.merged }}
    uses: ./.github/workflows/npm-publisher.yml
    with:
      action: deprecate
      version-tag: ${{ needs.get-pr-info.outputs.dev_channel }}
      version-expression: ">0.0.0-${{ needs.get-pr-info.outputs.dev_channel }}"
      deprecation-message: "Deprecated dev version"

  delete-comment:
    needs: [get-pr-info]
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Delete package dev channel PR comment
        uses: thollander/actions-comment-pull-request@v3
        env:
          DEV_CHANNEL: ${{ needs.get-pr-info.outputs.dev_channel }}
        with:
          message: |
            Published under `${{ env.DEV_CHANNEL }}` npm channel.
            ```sh
            $ sf plugins install sf-git-merge-driver@${{ env.DEV_CHANNEL }}
            ```
          comment-tag: dev-publish
          mode: delete
